# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNascimento():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_nascimento(self):
    self.driver.set_window_size(945, 1020)
    self.driver.get("https://petrolina.augeeducacional.com.br/")
    self.driver.find_element(By.ID, "login").send_keys("ananunes")
    self.driver.find_element(By.ID, "senha").send_keys("laura28042011")
    self.driver.find_element(By.CSS_SELECTOR, "#okLogon > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menuAcessoRestrito").click()
    self.driver.find_element(By.LINK_TEXT, "Gestão Escolar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".icon-eol1398").click()
    self.driver.find_element(By.XPATH, "//div[3]/div/div/div/div[2]").click()
    self.driver.find_element(By.XPATH, "//ul/li").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.NAME, "nomeConsultar").click()
    self.driver.find_element(By.NAME, "nomeConsultar").send_keys("davi")
    self.driver.find_element(By.CSS_SELECTOR, "#lnk_pesquisar > img").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > .texto:nth-child(4) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > .texto:nth-child(4) > label").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > .texto:nth-child(4) > label").click()
  
